name: New version check
on:
  schedule:
  - cron: 0 16 * * *
  push:
    branches:
      - main

jobs:
  check:
    name: Check new version of natmap
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: EkkoG/latest-file-checker@main
        env:
          COMMIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAKEFILE: MetaCubeX-geodata/Makefile
          REPO: MetaCubeX/meta-rules-dat
          VERSION_FILED: GEOIP_VER
          HASH_FILED: GEOIP_FILE_HASH
          SOURCE_URL: https://github.com/{{repo}}/raw/release/geoip.dat
          BRANCH: main

      - uses: EkkoG/latest-file-checker@main
        env:
          COMMIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAKEFILE: MetaCubeX-geodata/Makefile
          REPO: MetaCubeX/meta-rules-dat
          VERSION_FILED: GEOSITE_VER
          HASH_FILED: GEOSITE_FILE_HASH
          SOURCE_URL: https://github.com/{{repo}}/raw/release/geosite.dat
          BRANCH: main

      - uses: EkkoG/latest-file-checker@main
        env:
          COMMIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAKEFILE: Loyalsoldier-geodata/Makefile
          REPO: Loyalsoldier/v2ray-rules-dat
          VERSION_FILED: GEOIP_VER
          HASH_FILED: GEOIP_FILE_HASH
          SOURCE_URL: https://github.com/{{repo}}/releases/download/{{version}}/geoip.dat
          BRANCH: main

      - uses: EkkoG/latest-file-checker@main
        env:
          COMMIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAKEFILE: Loyalsoldier-geodata/Makefile
          REPO: Loyalsoldier/v2ray-rules-dat
          VERSION_FILED: GEOSITE_VER
          HASH_FILED: GEOSITE_FILE_HASH
          SOURCE_URL: https://github.com/{{repo}}/releases/download/{{version}}/geosite.dat
          BRANCH: main

      - uses: EkkoG/latest-file-checker@main
        env:
          COMMIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAKEFILE: Loyalsoldier-geodata/Makefile
          REPO: v2fly/geoip
          VERSION_FILED: GEOIP_VER
          HASH_FILED: GEOIP_FILE_HASH
          SOURCE_URL: https://github.com/{{repo}}/releases/download/{{version}}/geoip.dat
          BRANCH: main

      - uses: EkkoG/latest-file-checker@main
        env:
          COMMIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAKEFILE: v2ray-geodata/Makefile
          REPO: v2fly/domain-list-community
          VERSION_FILED: GEOSITE_VER
          HASH_FILED: GEOSITE_FILE_HASH
          SOURCE_URL: https://github.com/{{repo}}/releases/download/{{version}}/dlc.dat
          BRANCH: main